name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.8' 

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install ajv@latest 
          npm install ajv-keywords@latest 
          npm ci

      - name: Build Project
        run: npm run build
        
      - name: Authenticate with OIDC
        uses: aws-actions/aws-oidc@v1
        with:
          oidc-url: ${{ secrets.OIDC_URL }}
          role-arn: arn:aws:iam::533267328352:role/OIDCforGitHub # ARN of the IAM role you created

      - name: Configure AWS Credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ steps.oidc.outputs.role-to-assume }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: 'build'
          
      - name: Verify Deployment
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}/
        
      - name: Display Website URL
        run: echo "Your website is hosted at http://${{ secrets.AWS_S3_BUCKET }}.s3-website-${{ vars.AWS_REGION }}.amazonaws.com"
